### ISSUE TITLE
CocInstall error on activate extension: problem with scoped package

### ISSUE THREAD

**Issue by pappasam** [yaegassy/coc-nginx#9]
Problem: the scoped package causes issues with CocInstall.

OS: Ubuntu 20.0.4
Editor: Neovim nightly
Terminal: Alacritty
Coc version: latest release

I've added '@yaegassy/coc-nginx' to `g:coc_global_extensions` (which automatically calls `CocInstall @yaegassy/coc-nginx`. After it's installed, I get the following error:

`[coc.nvim] Error on activate extension @yaegassy/coc-nginx: ENOENT: no such file or directory, mkdir '~/config/coc/extensions/@yaegassy/coc-nginx-data'`

When going into my `.config` directory, I see that `coc-nginx` is placed at the `extensions` location:

![image](https://user-images.githubusercontent.com/3723671/132735351-825c9053-26f6-4715-b4f6-e9e3a5f48b19.png)

**Comment by pappasam** [comment]
Same error actually takes place when I install with yarn.

**Comment by yaegassy** [comment]
Hi, @pappasam 

Thanks for the bug report! I fixed it. 🙇

**Comment by pappasam** [comment]
Thanks for handling quickly, I confirm the latest release works!
